feishuToken: 
filterSearch:
  - 漏洞
  - 分析
sqlDataName: ./rssData
sqlTableName: rssTable
sqlCretaTable: CREATE TABLE rssTable ( id integer primary key autoincrement, title TEXT(15) not null,link TEXT(15) not null, date TEXT(15) not null,rssName TEXT(15) not null);
