targetPath: /api.json
targetMethod: get
targetTimeout: 1
targetProfixs:
    http: 127.0.0.1:7890
    https: 127.0.0.1:7890
targetAllowRedirects: false
targetHeaders:
    User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:102.0) Gecko/20100101 Firefox/102.0
targetJson:
targetData:
targetReExpression:
    respStatusCode: 200
targetDir: ../countryQueryResult/
targetOutputDir: ../2CVE漏洞POC目标/Swagger_apiJson/
targetRestText: 2